// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: audio_recognition.proto

#ifndef PROTOBUF_audio_5frecognition_2eproto__INCLUDED
#define PROTOBUF_audio_5frecognition_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "response.pb.h"
// @@protoc_insertion_point(includes)
class AddDataResponse;
class AddDataResponseDefaultTypeInternal;
extern AddDataResponseDefaultTypeInternal _AddDataResponse_default_instance_;
class ConnectionResponse;
class ConnectionResponseDefaultTypeInternal;
extern ConnectionResponseDefaultTypeInternal _ConnectionResponse_default_instance_;
class Result;
class ResultDefaultTypeInternal;
extern ResultDefaultTypeInternal _Result_default_instance_;
class Word;
class WordDefaultTypeInternal;
extern WordDefaultTypeInternal _Word_default_instance_;

namespace protobuf_audio_5frecognition_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_audio_5frecognition_2eproto

// ===================================================================

class Word : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Word) */ {
 public:
  Word();
  virtual ~Word();

  Word(const Word& from);

  inline Word& operator=(const Word& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Word& default_instance();

  static inline const Word* internal_default_instance() {
    return reinterpret_cast<const Word*>(
               &_Word_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Word* other);

  // implements Message ----------------------------------------------

  inline Word* New() const PROTOBUF_FINAL { return New(NULL); }

  Word* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Word& from);
  void MergeFrom(const Word& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Word* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // required float confidence = 1;
  bool has_confidence() const;
  void clear_confidence();
  static const int kConfidenceFieldNumber = 1;
  float confidence() const;
  void set_confidence(float value);

  // @@protoc_insertion_point(class_scope:Word)
 private:
  void set_has_confidence();
  void clear_has_confidence();
  void set_has_value();
  void clear_has_value();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  float confidence_;
  friend struct protobuf_audio_5frecognition_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Result : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Result) */ {
 public:
  Result();
  virtual ~Result();

  Result(const Result& from);

  inline Result& operator=(const Result& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Result& default_instance();

  static inline const Result* internal_default_instance() {
    return reinterpret_cast<const Result*>(
               &_Result_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Result* other);

  // implements Message ----------------------------------------------

  inline Result* New() const PROTOBUF_FINAL { return New(NULL); }

  Result* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Result& from);
  void MergeFrom(const Result& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Result* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Word words = 2;
  int words_size() const;
  void clear_words();
  static const int kWordsFieldNumber = 2;
  const ::Word& words(int index) const;
  ::Word* mutable_words(int index);
  ::Word* add_words();
  ::google::protobuf::RepeatedPtrField< ::Word >*
      mutable_words();
  const ::google::protobuf::RepeatedPtrField< ::Word >&
      words() const;

  // optional string normalized = 3;
  bool has_normalized() const;
  void clear_normalized();
  static const int kNormalizedFieldNumber = 3;
  const ::std::string& normalized() const;
  void set_normalized(const ::std::string& value);
  #if LANG_CXX11
  void set_normalized(::std::string&& value);
  #endif
  void set_normalized(const char* value);
  void set_normalized(const char* value, size_t size);
  ::std::string* mutable_normalized();
  ::std::string* release_normalized();
  void set_allocated_normalized(::std::string* normalized);

  // required float confidence = 1;
  bool has_confidence() const;
  void clear_confidence();
  static const int kConfidenceFieldNumber = 1;
  float confidence() const;
  void set_confidence(float value);

  // @@protoc_insertion_point(class_scope:Result)
 private:
  void set_has_confidence();
  void clear_has_confidence();
  void set_has_normalized();
  void clear_has_normalized();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Word > words_;
  ::google::protobuf::internal::ArenaStringPtr normalized_;
  float confidence_;
  friend struct protobuf_audio_5frecognition_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AddDataResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AddDataResponse) */ {
 public:
  AddDataResponse();
  virtual ~AddDataResponse();

  AddDataResponse(const AddDataResponse& from);

  inline AddDataResponse& operator=(const AddDataResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AddDataResponse& default_instance();

  static inline const AddDataResponse* internal_default_instance() {
    return reinterpret_cast<const AddDataResponse*>(
               &_AddDataResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(AddDataResponse* other);

  // implements Message ----------------------------------------------

  inline AddDataResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  AddDataResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AddDataResponse& from);
  void MergeFrom(const AddDataResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AddDataResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Result recognition = 2;
  int recognition_size() const;
  void clear_recognition();
  static const int kRecognitionFieldNumber = 2;
  const ::Result& recognition(int index) const;
  ::Result* mutable_recognition(int index);
  ::Result* add_recognition();
  ::google::protobuf::RepeatedPtrField< ::Result >*
      mutable_recognition();
  const ::google::protobuf::RepeatedPtrField< ::Result >&
      recognition() const;

  // optional bool endOfUtt = 3 [default = false];
  bool has_endofutt() const;
  void clear_endofutt();
  static const int kEndOfUttFieldNumber = 3;
  bool endofutt() const;
  void set_endofutt(bool value);

  // required .ConnectionResponse.ResponseCode responseCode = 1;
  bool has_responsecode() const;
  void clear_responsecode();
  static const int kResponseCodeFieldNumber = 1;
  ::ConnectionResponse_ResponseCode responsecode() const;
  void set_responsecode(::ConnectionResponse_ResponseCode value);

  // optional int32 messagesCount = 4 [default = 1];
  bool has_messagescount() const;
  void clear_messagescount();
  static const int kMessagesCountFieldNumber = 4;
  ::google::protobuf::int32 messagescount() const;
  void set_messagescount(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:AddDataResponse)
 private:
  void set_has_responsecode();
  void clear_has_responsecode();
  void set_has_endofutt();
  void clear_has_endofutt();
  void set_has_messagescount();
  void clear_has_messagescount();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Result > recognition_;
  bool endofutt_;
  int responsecode_;
  ::google::protobuf::int32 messagescount_;
  friend struct protobuf_audio_5frecognition_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Word

// required float confidence = 1;
inline bool Word::has_confidence() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Word::set_has_confidence() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Word::clear_has_confidence() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Word::clear_confidence() {
  confidence_ = 0;
  clear_has_confidence();
}
inline float Word::confidence() const {
  // @@protoc_insertion_point(field_get:Word.confidence)
  return confidence_;
}
inline void Word::set_confidence(float value) {
  set_has_confidence();
  confidence_ = value;
  // @@protoc_insertion_point(field_set:Word.confidence)
}

// required string value = 2;
inline bool Word::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Word::set_has_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Word::clear_has_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Word::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& Word::value() const {
  // @@protoc_insertion_point(field_get:Word.value)
  return value_.GetNoArena();
}
inline void Word::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Word.value)
}
#if LANG_CXX11
inline void Word::set_value(::std::string&& value) {
  set_has_value();
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Word.value)
}
#endif
inline void Word::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Word.value)
}
inline void Word::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Word.value)
}
inline ::std::string* Word::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:Word.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Word::release_value() {
  // @@protoc_insertion_point(field_release:Word.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Word::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:Word.value)
}

// -------------------------------------------------------------------

// Result

// required float confidence = 1;
inline bool Result::has_confidence() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Result::set_has_confidence() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Result::clear_has_confidence() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Result::clear_confidence() {
  confidence_ = 0;
  clear_has_confidence();
}
inline float Result::confidence() const {
  // @@protoc_insertion_point(field_get:Result.confidence)
  return confidence_;
}
inline void Result::set_confidence(float value) {
  set_has_confidence();
  confidence_ = value;
  // @@protoc_insertion_point(field_set:Result.confidence)
}

// repeated .Word words = 2;
inline int Result::words_size() const {
  return words_.size();
}
inline void Result::clear_words() {
  words_.Clear();
}
inline const ::Word& Result::words(int index) const {
  // @@protoc_insertion_point(field_get:Result.words)
  return words_.Get(index);
}
inline ::Word* Result::mutable_words(int index) {
  // @@protoc_insertion_point(field_mutable:Result.words)
  return words_.Mutable(index);
}
inline ::Word* Result::add_words() {
  // @@protoc_insertion_point(field_add:Result.words)
  return words_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Word >*
Result::mutable_words() {
  // @@protoc_insertion_point(field_mutable_list:Result.words)
  return &words_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Word >&
Result::words() const {
  // @@protoc_insertion_point(field_list:Result.words)
  return words_;
}

// optional string normalized = 3;
inline bool Result::has_normalized() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Result::set_has_normalized() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Result::clear_has_normalized() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Result::clear_normalized() {
  normalized_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_normalized();
}
inline const ::std::string& Result::normalized() const {
  // @@protoc_insertion_point(field_get:Result.normalized)
  return normalized_.GetNoArena();
}
inline void Result::set_normalized(const ::std::string& value) {
  set_has_normalized();
  normalized_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Result.normalized)
}
#if LANG_CXX11
inline void Result::set_normalized(::std::string&& value) {
  set_has_normalized();
  normalized_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Result.normalized)
}
#endif
inline void Result::set_normalized(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_normalized();
  normalized_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Result.normalized)
}
inline void Result::set_normalized(const char* value, size_t size) {
  set_has_normalized();
  normalized_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Result.normalized)
}
inline ::std::string* Result::mutable_normalized() {
  set_has_normalized();
  // @@protoc_insertion_point(field_mutable:Result.normalized)
  return normalized_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Result::release_normalized() {
  // @@protoc_insertion_point(field_release:Result.normalized)
  clear_has_normalized();
  return normalized_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Result::set_allocated_normalized(::std::string* normalized) {
  if (normalized != NULL) {
    set_has_normalized();
  } else {
    clear_has_normalized();
  }
  normalized_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), normalized);
  // @@protoc_insertion_point(field_set_allocated:Result.normalized)
}

// -------------------------------------------------------------------

// AddDataResponse

// required .ConnectionResponse.ResponseCode responseCode = 1;
inline bool AddDataResponse::has_responsecode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AddDataResponse::set_has_responsecode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AddDataResponse::clear_has_responsecode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AddDataResponse::clear_responsecode() {
  responsecode_ = 200;
  clear_has_responsecode();
}
inline ::ConnectionResponse_ResponseCode AddDataResponse::responsecode() const {
  // @@protoc_insertion_point(field_get:AddDataResponse.responseCode)
  return static_cast< ::ConnectionResponse_ResponseCode >(responsecode_);
}
inline void AddDataResponse::set_responsecode(::ConnectionResponse_ResponseCode value) {
  assert(::ConnectionResponse_ResponseCode_IsValid(value));
  set_has_responsecode();
  responsecode_ = value;
  // @@protoc_insertion_point(field_set:AddDataResponse.responseCode)
}

// repeated .Result recognition = 2;
inline int AddDataResponse::recognition_size() const {
  return recognition_.size();
}
inline void AddDataResponse::clear_recognition() {
  recognition_.Clear();
}
inline const ::Result& AddDataResponse::recognition(int index) const {
  // @@protoc_insertion_point(field_get:AddDataResponse.recognition)
  return recognition_.Get(index);
}
inline ::Result* AddDataResponse::mutable_recognition(int index) {
  // @@protoc_insertion_point(field_mutable:AddDataResponse.recognition)
  return recognition_.Mutable(index);
}
inline ::Result* AddDataResponse::add_recognition() {
  // @@protoc_insertion_point(field_add:AddDataResponse.recognition)
  return recognition_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Result >*
AddDataResponse::mutable_recognition() {
  // @@protoc_insertion_point(field_mutable_list:AddDataResponse.recognition)
  return &recognition_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Result >&
AddDataResponse::recognition() const {
  // @@protoc_insertion_point(field_list:AddDataResponse.recognition)
  return recognition_;
}

// optional bool endOfUtt = 3 [default = false];
inline bool AddDataResponse::has_endofutt() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AddDataResponse::set_has_endofutt() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AddDataResponse::clear_has_endofutt() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AddDataResponse::clear_endofutt() {
  endofutt_ = false;
  clear_has_endofutt();
}
inline bool AddDataResponse::endofutt() const {
  // @@protoc_insertion_point(field_get:AddDataResponse.endOfUtt)
  return endofutt_;
}
inline void AddDataResponse::set_endofutt(bool value) {
  set_has_endofutt();
  endofutt_ = value;
  // @@protoc_insertion_point(field_set:AddDataResponse.endOfUtt)
}

// optional int32 messagesCount = 4 [default = 1];
inline bool AddDataResponse::has_messagescount() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AddDataResponse::set_has_messagescount() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AddDataResponse::clear_has_messagescount() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AddDataResponse::clear_messagescount() {
  messagescount_ = 1;
  clear_has_messagescount();
}
inline ::google::protobuf::int32 AddDataResponse::messagescount() const {
  // @@protoc_insertion_point(field_get:AddDataResponse.messagesCount)
  return messagescount_;
}
inline void AddDataResponse::set_messagescount(::google::protobuf::int32 value) {
  set_has_messagescount();
  messagescount_ = value;
  // @@protoc_insertion_point(field_set:AddDataResponse.messagesCount)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_audio_5frecognition_2eproto__INCLUDED
