// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "request.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class ConnectionRequestDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ConnectionRequest> {
} _ConnectionRequest_default_instance_;
class AdvancedASROptionsDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<AdvancedASROptions> {
} _AdvancedASROptions_default_instance_;

namespace protobuf_request_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, protocolversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, speechkitversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, servicename_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, uuid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, apikey_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, applicationname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, device_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, coords_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, topic_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, lang_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, format_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionRequest, advancedasroptions_),
  11,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdvancedASROptions, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdvancedASROptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdvancedASROptions, partial_results_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AdvancedASROptions, biometry_),
  1,
  0,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 17, sizeof(ConnectionRequest)},
  { 29, 36, sizeof(AdvancedASROptions)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_ConnectionRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_AdvancedASROptions_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "request.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _ConnectionRequest_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _AdvancedASROptions_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _ConnectionRequest_default_instance_.DefaultConstruct();
  _AdvancedASROptions_default_instance_.DefaultConstruct();
  _ConnectionRequest_default_instance_.get_mutable()->advancedasroptions_ = const_cast< ::AdvancedASROptions*>(
      ::AdvancedASROptions::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\rrequest.proto\"\223\002\n\021ConnectionRequest\022\032\n"
      "\017protocolVersion\030\001 \001(\005:\0011\022\030\n\020speechkitVe"
      "rsion\030\002 \002(\t\022\023\n\013serviceName\030\003 \002(\t\022\014\n\004uuid"
      "\030\004 \002(\t\022\016\n\006apiKey\030\005 \002(\t\022\027\n\017applicationNam"
      "e\030\006 \002(\t\022\016\n\006device\030\007 \002(\t\022\016\n\006coords\030\010 \002(\t\022"
      "\r\n\005topic\030\t \002(\t\022\014\n\004lang\030\n \002(\t\022\016\n\006format\030\013"
      " \002(\t\022/\n\022advancedASROptions\030\023 \001(\0132\023.Advan"
      "cedASROptions\"E\n\022AdvancedASROptions\022\035\n\017p"
      "artial_results\030\001 \001(\010:\004true\022\020\n\010biometry\030\030"
      " \001(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 364);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "request.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_request_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConnectionRequest::kProtocolVersionFieldNumber;
const int ConnectionRequest::kSpeechkitVersionFieldNumber;
const int ConnectionRequest::kServiceNameFieldNumber;
const int ConnectionRequest::kUuidFieldNumber;
const int ConnectionRequest::kApiKeyFieldNumber;
const int ConnectionRequest::kApplicationNameFieldNumber;
const int ConnectionRequest::kDeviceFieldNumber;
const int ConnectionRequest::kCoordsFieldNumber;
const int ConnectionRequest::kTopicFieldNumber;
const int ConnectionRequest::kLangFieldNumber;
const int ConnectionRequest::kFormatFieldNumber;
const int ConnectionRequest::kAdvancedASROptionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConnectionRequest::ConnectionRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_request_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ConnectionRequest)
}
ConnectionRequest::ConnectionRequest(const ConnectionRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  speechkitversion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_speechkitversion()) {
    speechkitversion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.speechkitversion_);
  }
  servicename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_servicename()) {
    servicename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.servicename_);
  }
  uuid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_uuid()) {
    uuid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.uuid_);
  }
  apikey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_apikey()) {
    apikey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.apikey_);
  }
  applicationname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_applicationname()) {
    applicationname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.applicationname_);
  }
  device_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_device()) {
    device_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.device_);
  }
  coords_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_coords()) {
    coords_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.coords_);
  }
  topic_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_topic()) {
    topic_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.topic_);
  }
  lang_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_lang()) {
    lang_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lang_);
  }
  format_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_format()) {
    format_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.format_);
  }
  if (from.has_advancedasroptions()) {
    advancedasroptions_ = new ::AdvancedASROptions(*from.advancedasroptions_);
  } else {
    advancedasroptions_ = NULL;
  }
  protocolversion_ = from.protocolversion_;
  // @@protoc_insertion_point(copy_constructor:ConnectionRequest)
}

void ConnectionRequest::SharedCtor() {
  _cached_size_ = 0;
  speechkitversion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  servicename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uuid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  apikey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  applicationname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  device_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  coords_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  topic_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lang_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  advancedasroptions_ = NULL;
  protocolversion_ = 1;
}

ConnectionRequest::~ConnectionRequest() {
  // @@protoc_insertion_point(destructor:ConnectionRequest)
  SharedDtor();
}

void ConnectionRequest::SharedDtor() {
  speechkitversion_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  servicename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uuid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  apikey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  applicationname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  device_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  coords_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  topic_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lang_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete advancedasroptions_;
  }
}

void ConnectionRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ConnectionRequest::descriptor() {
  protobuf_request_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_request_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ConnectionRequest& ConnectionRequest::default_instance() {
  protobuf_request_2eproto::InitDefaults();
  return *internal_default_instance();
}

ConnectionRequest* ConnectionRequest::New(::google::protobuf::Arena* arena) const {
  ConnectionRequest* n = new ConnectionRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ConnectionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ConnectionRequest)
  if (_has_bits_[0 / 32] & 255u) {
    if (has_speechkitversion()) {
      GOOGLE_DCHECK(!speechkitversion_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*speechkitversion_.UnsafeRawStringPointer())->clear();
    }
    if (has_servicename()) {
      GOOGLE_DCHECK(!servicename_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*servicename_.UnsafeRawStringPointer())->clear();
    }
    if (has_uuid()) {
      GOOGLE_DCHECK(!uuid_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*uuid_.UnsafeRawStringPointer())->clear();
    }
    if (has_apikey()) {
      GOOGLE_DCHECK(!apikey_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*apikey_.UnsafeRawStringPointer())->clear();
    }
    if (has_applicationname()) {
      GOOGLE_DCHECK(!applicationname_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*applicationname_.UnsafeRawStringPointer())->clear();
    }
    if (has_device()) {
      GOOGLE_DCHECK(!device_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*device_.UnsafeRawStringPointer())->clear();
    }
    if (has_coords()) {
      GOOGLE_DCHECK(!coords_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*coords_.UnsafeRawStringPointer())->clear();
    }
    if (has_topic()) {
      GOOGLE_DCHECK(!topic_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*topic_.UnsafeRawStringPointer())->clear();
    }
  }
  if (_has_bits_[8 / 32] & 3840u) {
    if (has_lang()) {
      GOOGLE_DCHECK(!lang_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*lang_.UnsafeRawStringPointer())->clear();
    }
    if (has_format()) {
      GOOGLE_DCHECK(!format_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*format_.UnsafeRawStringPointer())->clear();
    }
    if (has_advancedasroptions()) {
      GOOGLE_DCHECK(advancedasroptions_ != NULL);
      advancedasroptions_->::AdvancedASROptions::Clear();
    }
    protocolversion_ = 1;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ConnectionRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ConnectionRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 protocolVersion = 1 [default = 1];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_protocolversion();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &protocolversion_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string speechkitVersion = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_speechkitversion()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->speechkitversion().data(), this->speechkitversion().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ConnectionRequest.speechkitVersion");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string serviceName = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_servicename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->servicename().data(), this->servicename().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ConnectionRequest.serviceName");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string uuid = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_uuid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->uuid().data(), this->uuid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ConnectionRequest.uuid");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string apiKey = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_apikey()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->apikey().data(), this->apikey().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ConnectionRequest.apiKey");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string applicationName = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_applicationname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->applicationname().data(), this->applicationname().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ConnectionRequest.applicationName");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string device = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_device()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->device().data(), this->device().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ConnectionRequest.device");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string coords = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_coords()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->coords().data(), this->coords().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ConnectionRequest.coords");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string topic = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_topic()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->topic().data(), this->topic().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ConnectionRequest.topic");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string lang = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_lang()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->lang().data(), this->lang().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ConnectionRequest.lang");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string format = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_format()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->format().data(), this->format().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ConnectionRequest.format");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .AdvancedASROptions advancedASROptions = 19;
      case 19: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(154u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_advancedasroptions()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ConnectionRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ConnectionRequest)
  return false;
#undef DO_
}

void ConnectionRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ConnectionRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 protocolVersion = 1 [default = 1];
  if (cached_has_bits & 0x00000800u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->protocolversion(), output);
  }

  // required string speechkitVersion = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->speechkitversion().data(), this->speechkitversion().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.speechkitVersion");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->speechkitversion(), output);
  }

  // required string serviceName = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->servicename().data(), this->servicename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.serviceName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->servicename(), output);
  }

  // required string uuid = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->uuid().data(), this->uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.uuid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->uuid(), output);
  }

  // required string apiKey = 5;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->apikey().data(), this->apikey().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.apiKey");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->apikey(), output);
  }

  // required string applicationName = 6;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->applicationname().data(), this->applicationname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.applicationName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->applicationname(), output);
  }

  // required string device = 7;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->device().data(), this->device().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.device");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->device(), output);
  }

  // required string coords = 8;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->coords().data(), this->coords().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.coords");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->coords(), output);
  }

  // required string topic = 9;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->topic().data(), this->topic().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.topic");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->topic(), output);
  }

  // required string lang = 10;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->lang().data(), this->lang().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.lang");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->lang(), output);
  }

  // required string format = 11;
  if (cached_has_bits & 0x00000200u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->format().data(), this->format().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.format");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->format(), output);
  }

  // optional .AdvancedASROptions advancedASROptions = 19;
  if (cached_has_bits & 0x00000400u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      19, *this->advancedasroptions_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ConnectionRequest)
}

::google::protobuf::uint8* ConnectionRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ConnectionRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 protocolVersion = 1 [default = 1];
  if (cached_has_bits & 0x00000800u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->protocolversion(), target);
  }

  // required string speechkitVersion = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->speechkitversion().data(), this->speechkitversion().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.speechkitVersion");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->speechkitversion(), target);
  }

  // required string serviceName = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->servicename().data(), this->servicename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.serviceName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->servicename(), target);
  }

  // required string uuid = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->uuid().data(), this->uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.uuid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->uuid(), target);
  }

  // required string apiKey = 5;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->apikey().data(), this->apikey().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.apiKey");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->apikey(), target);
  }

  // required string applicationName = 6;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->applicationname().data(), this->applicationname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.applicationName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->applicationname(), target);
  }

  // required string device = 7;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->device().data(), this->device().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.device");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->device(), target);
  }

  // required string coords = 8;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->coords().data(), this->coords().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.coords");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->coords(), target);
  }

  // required string topic = 9;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->topic().data(), this->topic().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.topic");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->topic(), target);
  }

  // required string lang = 10;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->lang().data(), this->lang().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.lang");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->lang(), target);
  }

  // required string format = 11;
  if (cached_has_bits & 0x00000200u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->format().data(), this->format().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ConnectionRequest.format");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->format(), target);
  }

  // optional .AdvancedASROptions advancedASROptions = 19;
  if (cached_has_bits & 0x00000400u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        19, *this->advancedasroptions_, deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ConnectionRequest)
  return target;
}

size_t ConnectionRequest::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:ConnectionRequest)
  size_t total_size = 0;

  if (has_speechkitversion()) {
    // required string speechkitVersion = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->speechkitversion());
  }

  if (has_servicename()) {
    // required string serviceName = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->servicename());
  }

  if (has_uuid()) {
    // required string uuid = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->uuid());
  }

  if (has_apikey()) {
    // required string apiKey = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->apikey());
  }

  if (has_applicationname()) {
    // required string applicationName = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->applicationname());
  }

  if (has_device()) {
    // required string device = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->device());
  }

  if (has_coords()) {
    // required string coords = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->coords());
  }

  if (has_topic()) {
    // required string topic = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->topic());
  }

  if (has_lang()) {
    // required string lang = 10;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->lang());
  }

  if (has_format()) {
    // required string format = 11;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->format());
  }

  return total_size;
}
size_t ConnectionRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ConnectionRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x000003ff) ^ 0x000003ff) == 0) {  // All required fields are present.
    // required string speechkitVersion = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->speechkitversion());

    // required string serviceName = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->servicename());

    // required string uuid = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->uuid());

    // required string apiKey = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->apikey());

    // required string applicationName = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->applicationname());

    // required string device = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->device());

    // required string coords = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->coords());

    // required string topic = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->topic());

    // required string lang = 10;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->lang());

    // required string format = 11;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->format());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_has_bits_[8 / 32] & 3072u) {
    // optional .AdvancedASROptions advancedASROptions = 19;
    if (has_advancedasroptions()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->advancedasroptions_);
    }

    // optional int32 protocolVersion = 1 [default = 1];
    if (has_protocolversion()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->protocolversion());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ConnectionRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ConnectionRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ConnectionRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConnectionRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ConnectionRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ConnectionRequest)
    MergeFrom(*source);
  }
}

void ConnectionRequest::MergeFrom(const ConnectionRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ConnectionRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_speechkitversion();
      speechkitversion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.speechkitversion_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_servicename();
      servicename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.servicename_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_uuid();
      uuid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.uuid_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_apikey();
      apikey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.apikey_);
    }
    if (cached_has_bits & 0x00000010u) {
      set_has_applicationname();
      applicationname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.applicationname_);
    }
    if (cached_has_bits & 0x00000020u) {
      set_has_device();
      device_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.device_);
    }
    if (cached_has_bits & 0x00000040u) {
      set_has_coords();
      coords_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.coords_);
    }
    if (cached_has_bits & 0x00000080u) {
      set_has_topic();
      topic_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.topic_);
    }
  }
  if (cached_has_bits & 3840u) {
    if (cached_has_bits & 0x00000100u) {
      set_has_lang();
      lang_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lang_);
    }
    if (cached_has_bits & 0x00000200u) {
      set_has_format();
      format_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.format_);
    }
    if (cached_has_bits & 0x00000400u) {
      mutable_advancedasroptions()->::AdvancedASROptions::MergeFrom(from.advancedasroptions());
    }
    if (cached_has_bits & 0x00000800u) {
      protocolversion_ = from.protocolversion_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ConnectionRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ConnectionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConnectionRequest::CopyFrom(const ConnectionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ConnectionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConnectionRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x000003ff) != 0x000003ff) return false;
  return true;
}

void ConnectionRequest::Swap(ConnectionRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConnectionRequest::InternalSwap(ConnectionRequest* other) {
  speechkitversion_.Swap(&other->speechkitversion_);
  servicename_.Swap(&other->servicename_);
  uuid_.Swap(&other->uuid_);
  apikey_.Swap(&other->apikey_);
  applicationname_.Swap(&other->applicationname_);
  device_.Swap(&other->device_);
  coords_.Swap(&other->coords_);
  topic_.Swap(&other->topic_);
  lang_.Swap(&other->lang_);
  format_.Swap(&other->format_);
  std::swap(advancedasroptions_, other->advancedasroptions_);
  std::swap(protocolversion_, other->protocolversion_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ConnectionRequest::GetMetadata() const {
  protobuf_request_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_request_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ConnectionRequest

// optional int32 protocolVersion = 1 [default = 1];
bool ConnectionRequest::has_protocolversion() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
void ConnectionRequest::set_has_protocolversion() {
  _has_bits_[0] |= 0x00000800u;
}
void ConnectionRequest::clear_has_protocolversion() {
  _has_bits_[0] &= ~0x00000800u;
}
void ConnectionRequest::clear_protocolversion() {
  protocolversion_ = 1;
  clear_has_protocolversion();
}
::google::protobuf::int32 ConnectionRequest::protocolversion() const {
  // @@protoc_insertion_point(field_get:ConnectionRequest.protocolVersion)
  return protocolversion_;
}
void ConnectionRequest::set_protocolversion(::google::protobuf::int32 value) {
  set_has_protocolversion();
  protocolversion_ = value;
  // @@protoc_insertion_point(field_set:ConnectionRequest.protocolVersion)
}

// required string speechkitVersion = 2;
bool ConnectionRequest::has_speechkitversion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ConnectionRequest::set_has_speechkitversion() {
  _has_bits_[0] |= 0x00000001u;
}
void ConnectionRequest::clear_has_speechkitversion() {
  _has_bits_[0] &= ~0x00000001u;
}
void ConnectionRequest::clear_speechkitversion() {
  speechkitversion_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_speechkitversion();
}
const ::std::string& ConnectionRequest::speechkitversion() const {
  // @@protoc_insertion_point(field_get:ConnectionRequest.speechkitVersion)
  return speechkitversion_.GetNoArena();
}
void ConnectionRequest::set_speechkitversion(const ::std::string& value) {
  set_has_speechkitversion();
  speechkitversion_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ConnectionRequest.speechkitVersion)
}
#if LANG_CXX11
void ConnectionRequest::set_speechkitversion(::std::string&& value) {
  set_has_speechkitversion();
  speechkitversion_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ConnectionRequest.speechkitVersion)
}
#endif
void ConnectionRequest::set_speechkitversion(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_speechkitversion();
  speechkitversion_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ConnectionRequest.speechkitVersion)
}
void ConnectionRequest::set_speechkitversion(const char* value, size_t size) {
  set_has_speechkitversion();
  speechkitversion_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ConnectionRequest.speechkitVersion)
}
::std::string* ConnectionRequest::mutable_speechkitversion() {
  set_has_speechkitversion();
  // @@protoc_insertion_point(field_mutable:ConnectionRequest.speechkitVersion)
  return speechkitversion_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ConnectionRequest::release_speechkitversion() {
  // @@protoc_insertion_point(field_release:ConnectionRequest.speechkitVersion)
  clear_has_speechkitversion();
  return speechkitversion_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ConnectionRequest::set_allocated_speechkitversion(::std::string* speechkitversion) {
  if (speechkitversion != NULL) {
    set_has_speechkitversion();
  } else {
    clear_has_speechkitversion();
  }
  speechkitversion_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), speechkitversion);
  // @@protoc_insertion_point(field_set_allocated:ConnectionRequest.speechkitVersion)
}

// required string serviceName = 3;
bool ConnectionRequest::has_servicename() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void ConnectionRequest::set_has_servicename() {
  _has_bits_[0] |= 0x00000002u;
}
void ConnectionRequest::clear_has_servicename() {
  _has_bits_[0] &= ~0x00000002u;
}
void ConnectionRequest::clear_servicename() {
  servicename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_servicename();
}
const ::std::string& ConnectionRequest::servicename() const {
  // @@protoc_insertion_point(field_get:ConnectionRequest.serviceName)
  return servicename_.GetNoArena();
}
void ConnectionRequest::set_servicename(const ::std::string& value) {
  set_has_servicename();
  servicename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ConnectionRequest.serviceName)
}
#if LANG_CXX11
void ConnectionRequest::set_servicename(::std::string&& value) {
  set_has_servicename();
  servicename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ConnectionRequest.serviceName)
}
#endif
void ConnectionRequest::set_servicename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_servicename();
  servicename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ConnectionRequest.serviceName)
}
void ConnectionRequest::set_servicename(const char* value, size_t size) {
  set_has_servicename();
  servicename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ConnectionRequest.serviceName)
}
::std::string* ConnectionRequest::mutable_servicename() {
  set_has_servicename();
  // @@protoc_insertion_point(field_mutable:ConnectionRequest.serviceName)
  return servicename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ConnectionRequest::release_servicename() {
  // @@protoc_insertion_point(field_release:ConnectionRequest.serviceName)
  clear_has_servicename();
  return servicename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ConnectionRequest::set_allocated_servicename(::std::string* servicename) {
  if (servicename != NULL) {
    set_has_servicename();
  } else {
    clear_has_servicename();
  }
  servicename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), servicename);
  // @@protoc_insertion_point(field_set_allocated:ConnectionRequest.serviceName)
}

// required string uuid = 4;
bool ConnectionRequest::has_uuid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void ConnectionRequest::set_has_uuid() {
  _has_bits_[0] |= 0x00000004u;
}
void ConnectionRequest::clear_has_uuid() {
  _has_bits_[0] &= ~0x00000004u;
}
void ConnectionRequest::clear_uuid() {
  uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_uuid();
}
const ::std::string& ConnectionRequest::uuid() const {
  // @@protoc_insertion_point(field_get:ConnectionRequest.uuid)
  return uuid_.GetNoArena();
}
void ConnectionRequest::set_uuid(const ::std::string& value) {
  set_has_uuid();
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ConnectionRequest.uuid)
}
#if LANG_CXX11
void ConnectionRequest::set_uuid(::std::string&& value) {
  set_has_uuid();
  uuid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ConnectionRequest.uuid)
}
#endif
void ConnectionRequest::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_uuid();
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ConnectionRequest.uuid)
}
void ConnectionRequest::set_uuid(const char* value, size_t size) {
  set_has_uuid();
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ConnectionRequest.uuid)
}
::std::string* ConnectionRequest::mutable_uuid() {
  set_has_uuid();
  // @@protoc_insertion_point(field_mutable:ConnectionRequest.uuid)
  return uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ConnectionRequest::release_uuid() {
  // @@protoc_insertion_point(field_release:ConnectionRequest.uuid)
  clear_has_uuid();
  return uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ConnectionRequest::set_allocated_uuid(::std::string* uuid) {
  if (uuid != NULL) {
    set_has_uuid();
  } else {
    clear_has_uuid();
  }
  uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uuid);
  // @@protoc_insertion_point(field_set_allocated:ConnectionRequest.uuid)
}

// required string apiKey = 5;
bool ConnectionRequest::has_apikey() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void ConnectionRequest::set_has_apikey() {
  _has_bits_[0] |= 0x00000008u;
}
void ConnectionRequest::clear_has_apikey() {
  _has_bits_[0] &= ~0x00000008u;
}
void ConnectionRequest::clear_apikey() {
  apikey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_apikey();
}
const ::std::string& ConnectionRequest::apikey() const {
  // @@protoc_insertion_point(field_get:ConnectionRequest.apiKey)
  return apikey_.GetNoArena();
}
void ConnectionRequest::set_apikey(const ::std::string& value) {
  set_has_apikey();
  apikey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ConnectionRequest.apiKey)
}
#if LANG_CXX11
void ConnectionRequest::set_apikey(::std::string&& value) {
  set_has_apikey();
  apikey_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ConnectionRequest.apiKey)
}
#endif
void ConnectionRequest::set_apikey(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_apikey();
  apikey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ConnectionRequest.apiKey)
}
void ConnectionRequest::set_apikey(const char* value, size_t size) {
  set_has_apikey();
  apikey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ConnectionRequest.apiKey)
}
::std::string* ConnectionRequest::mutable_apikey() {
  set_has_apikey();
  // @@protoc_insertion_point(field_mutable:ConnectionRequest.apiKey)
  return apikey_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ConnectionRequest::release_apikey() {
  // @@protoc_insertion_point(field_release:ConnectionRequest.apiKey)
  clear_has_apikey();
  return apikey_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ConnectionRequest::set_allocated_apikey(::std::string* apikey) {
  if (apikey != NULL) {
    set_has_apikey();
  } else {
    clear_has_apikey();
  }
  apikey_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), apikey);
  // @@protoc_insertion_point(field_set_allocated:ConnectionRequest.apiKey)
}

// required string applicationName = 6;
bool ConnectionRequest::has_applicationname() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void ConnectionRequest::set_has_applicationname() {
  _has_bits_[0] |= 0x00000010u;
}
void ConnectionRequest::clear_has_applicationname() {
  _has_bits_[0] &= ~0x00000010u;
}
void ConnectionRequest::clear_applicationname() {
  applicationname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_applicationname();
}
const ::std::string& ConnectionRequest::applicationname() const {
  // @@protoc_insertion_point(field_get:ConnectionRequest.applicationName)
  return applicationname_.GetNoArena();
}
void ConnectionRequest::set_applicationname(const ::std::string& value) {
  set_has_applicationname();
  applicationname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ConnectionRequest.applicationName)
}
#if LANG_CXX11
void ConnectionRequest::set_applicationname(::std::string&& value) {
  set_has_applicationname();
  applicationname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ConnectionRequest.applicationName)
}
#endif
void ConnectionRequest::set_applicationname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_applicationname();
  applicationname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ConnectionRequest.applicationName)
}
void ConnectionRequest::set_applicationname(const char* value, size_t size) {
  set_has_applicationname();
  applicationname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ConnectionRequest.applicationName)
}
::std::string* ConnectionRequest::mutable_applicationname() {
  set_has_applicationname();
  // @@protoc_insertion_point(field_mutable:ConnectionRequest.applicationName)
  return applicationname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ConnectionRequest::release_applicationname() {
  // @@protoc_insertion_point(field_release:ConnectionRequest.applicationName)
  clear_has_applicationname();
  return applicationname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ConnectionRequest::set_allocated_applicationname(::std::string* applicationname) {
  if (applicationname != NULL) {
    set_has_applicationname();
  } else {
    clear_has_applicationname();
  }
  applicationname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), applicationname);
  // @@protoc_insertion_point(field_set_allocated:ConnectionRequest.applicationName)
}

// required string device = 7;
bool ConnectionRequest::has_device() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void ConnectionRequest::set_has_device() {
  _has_bits_[0] |= 0x00000020u;
}
void ConnectionRequest::clear_has_device() {
  _has_bits_[0] &= ~0x00000020u;
}
void ConnectionRequest::clear_device() {
  device_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_device();
}
const ::std::string& ConnectionRequest::device() const {
  // @@protoc_insertion_point(field_get:ConnectionRequest.device)
  return device_.GetNoArena();
}
void ConnectionRequest::set_device(const ::std::string& value) {
  set_has_device();
  device_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ConnectionRequest.device)
}
#if LANG_CXX11
void ConnectionRequest::set_device(::std::string&& value) {
  set_has_device();
  device_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ConnectionRequest.device)
}
#endif
void ConnectionRequest::set_device(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_device();
  device_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ConnectionRequest.device)
}
void ConnectionRequest::set_device(const char* value, size_t size) {
  set_has_device();
  device_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ConnectionRequest.device)
}
::std::string* ConnectionRequest::mutable_device() {
  set_has_device();
  // @@protoc_insertion_point(field_mutable:ConnectionRequest.device)
  return device_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ConnectionRequest::release_device() {
  // @@protoc_insertion_point(field_release:ConnectionRequest.device)
  clear_has_device();
  return device_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ConnectionRequest::set_allocated_device(::std::string* device) {
  if (device != NULL) {
    set_has_device();
  } else {
    clear_has_device();
  }
  device_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device);
  // @@protoc_insertion_point(field_set_allocated:ConnectionRequest.device)
}

// required string coords = 8;
bool ConnectionRequest::has_coords() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void ConnectionRequest::set_has_coords() {
  _has_bits_[0] |= 0x00000040u;
}
void ConnectionRequest::clear_has_coords() {
  _has_bits_[0] &= ~0x00000040u;
}
void ConnectionRequest::clear_coords() {
  coords_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_coords();
}
const ::std::string& ConnectionRequest::coords() const {
  // @@protoc_insertion_point(field_get:ConnectionRequest.coords)
  return coords_.GetNoArena();
}
void ConnectionRequest::set_coords(const ::std::string& value) {
  set_has_coords();
  coords_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ConnectionRequest.coords)
}
#if LANG_CXX11
void ConnectionRequest::set_coords(::std::string&& value) {
  set_has_coords();
  coords_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ConnectionRequest.coords)
}
#endif
void ConnectionRequest::set_coords(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_coords();
  coords_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ConnectionRequest.coords)
}
void ConnectionRequest::set_coords(const char* value, size_t size) {
  set_has_coords();
  coords_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ConnectionRequest.coords)
}
::std::string* ConnectionRequest::mutable_coords() {
  set_has_coords();
  // @@protoc_insertion_point(field_mutable:ConnectionRequest.coords)
  return coords_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ConnectionRequest::release_coords() {
  // @@protoc_insertion_point(field_release:ConnectionRequest.coords)
  clear_has_coords();
  return coords_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ConnectionRequest::set_allocated_coords(::std::string* coords) {
  if (coords != NULL) {
    set_has_coords();
  } else {
    clear_has_coords();
  }
  coords_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), coords);
  // @@protoc_insertion_point(field_set_allocated:ConnectionRequest.coords)
}

// required string topic = 9;
bool ConnectionRequest::has_topic() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void ConnectionRequest::set_has_topic() {
  _has_bits_[0] |= 0x00000080u;
}
void ConnectionRequest::clear_has_topic() {
  _has_bits_[0] &= ~0x00000080u;
}
void ConnectionRequest::clear_topic() {
  topic_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_topic();
}
const ::std::string& ConnectionRequest::topic() const {
  // @@protoc_insertion_point(field_get:ConnectionRequest.topic)
  return topic_.GetNoArena();
}
void ConnectionRequest::set_topic(const ::std::string& value) {
  set_has_topic();
  topic_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ConnectionRequest.topic)
}
#if LANG_CXX11
void ConnectionRequest::set_topic(::std::string&& value) {
  set_has_topic();
  topic_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ConnectionRequest.topic)
}
#endif
void ConnectionRequest::set_topic(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_topic();
  topic_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ConnectionRequest.topic)
}
void ConnectionRequest::set_topic(const char* value, size_t size) {
  set_has_topic();
  topic_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ConnectionRequest.topic)
}
::std::string* ConnectionRequest::mutable_topic() {
  set_has_topic();
  // @@protoc_insertion_point(field_mutable:ConnectionRequest.topic)
  return topic_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ConnectionRequest::release_topic() {
  // @@protoc_insertion_point(field_release:ConnectionRequest.topic)
  clear_has_topic();
  return topic_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ConnectionRequest::set_allocated_topic(::std::string* topic) {
  if (topic != NULL) {
    set_has_topic();
  } else {
    clear_has_topic();
  }
  topic_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), topic);
  // @@protoc_insertion_point(field_set_allocated:ConnectionRequest.topic)
}

// required string lang = 10;
bool ConnectionRequest::has_lang() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
void ConnectionRequest::set_has_lang() {
  _has_bits_[0] |= 0x00000100u;
}
void ConnectionRequest::clear_has_lang() {
  _has_bits_[0] &= ~0x00000100u;
}
void ConnectionRequest::clear_lang() {
  lang_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_lang();
}
const ::std::string& ConnectionRequest::lang() const {
  // @@protoc_insertion_point(field_get:ConnectionRequest.lang)
  return lang_.GetNoArena();
}
void ConnectionRequest::set_lang(const ::std::string& value) {
  set_has_lang();
  lang_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ConnectionRequest.lang)
}
#if LANG_CXX11
void ConnectionRequest::set_lang(::std::string&& value) {
  set_has_lang();
  lang_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ConnectionRequest.lang)
}
#endif
void ConnectionRequest::set_lang(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_lang();
  lang_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ConnectionRequest.lang)
}
void ConnectionRequest::set_lang(const char* value, size_t size) {
  set_has_lang();
  lang_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ConnectionRequest.lang)
}
::std::string* ConnectionRequest::mutable_lang() {
  set_has_lang();
  // @@protoc_insertion_point(field_mutable:ConnectionRequest.lang)
  return lang_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ConnectionRequest::release_lang() {
  // @@protoc_insertion_point(field_release:ConnectionRequest.lang)
  clear_has_lang();
  return lang_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ConnectionRequest::set_allocated_lang(::std::string* lang) {
  if (lang != NULL) {
    set_has_lang();
  } else {
    clear_has_lang();
  }
  lang_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), lang);
  // @@protoc_insertion_point(field_set_allocated:ConnectionRequest.lang)
}

// required string format = 11;
bool ConnectionRequest::has_format() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
void ConnectionRequest::set_has_format() {
  _has_bits_[0] |= 0x00000200u;
}
void ConnectionRequest::clear_has_format() {
  _has_bits_[0] &= ~0x00000200u;
}
void ConnectionRequest::clear_format() {
  format_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_format();
}
const ::std::string& ConnectionRequest::format() const {
  // @@protoc_insertion_point(field_get:ConnectionRequest.format)
  return format_.GetNoArena();
}
void ConnectionRequest::set_format(const ::std::string& value) {
  set_has_format();
  format_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ConnectionRequest.format)
}
#if LANG_CXX11
void ConnectionRequest::set_format(::std::string&& value) {
  set_has_format();
  format_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ConnectionRequest.format)
}
#endif
void ConnectionRequest::set_format(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_format();
  format_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ConnectionRequest.format)
}
void ConnectionRequest::set_format(const char* value, size_t size) {
  set_has_format();
  format_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ConnectionRequest.format)
}
::std::string* ConnectionRequest::mutable_format() {
  set_has_format();
  // @@protoc_insertion_point(field_mutable:ConnectionRequest.format)
  return format_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ConnectionRequest::release_format() {
  // @@protoc_insertion_point(field_release:ConnectionRequest.format)
  clear_has_format();
  return format_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ConnectionRequest::set_allocated_format(::std::string* format) {
  if (format != NULL) {
    set_has_format();
  } else {
    clear_has_format();
  }
  format_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), format);
  // @@protoc_insertion_point(field_set_allocated:ConnectionRequest.format)
}

// optional .AdvancedASROptions advancedASROptions = 19;
bool ConnectionRequest::has_advancedasroptions() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
void ConnectionRequest::set_has_advancedasroptions() {
  _has_bits_[0] |= 0x00000400u;
}
void ConnectionRequest::clear_has_advancedasroptions() {
  _has_bits_[0] &= ~0x00000400u;
}
void ConnectionRequest::clear_advancedasroptions() {
  if (advancedasroptions_ != NULL) advancedasroptions_->::AdvancedASROptions::Clear();
  clear_has_advancedasroptions();
}
const ::AdvancedASROptions& ConnectionRequest::advancedasroptions() const {
  // @@protoc_insertion_point(field_get:ConnectionRequest.advancedASROptions)
  return advancedasroptions_ != NULL ? *advancedasroptions_
                         : *::AdvancedASROptions::internal_default_instance();
}
::AdvancedASROptions* ConnectionRequest::mutable_advancedasroptions() {
  set_has_advancedasroptions();
  if (advancedasroptions_ == NULL) {
    advancedasroptions_ = new ::AdvancedASROptions;
  }
  // @@protoc_insertion_point(field_mutable:ConnectionRequest.advancedASROptions)
  return advancedasroptions_;
}
::AdvancedASROptions* ConnectionRequest::release_advancedasroptions() {
  // @@protoc_insertion_point(field_release:ConnectionRequest.advancedASROptions)
  clear_has_advancedasroptions();
  ::AdvancedASROptions* temp = advancedasroptions_;
  advancedasroptions_ = NULL;
  return temp;
}
void ConnectionRequest::set_allocated_advancedasroptions(::AdvancedASROptions* advancedasroptions) {
  delete advancedasroptions_;
  advancedasroptions_ = advancedasroptions;
  if (advancedasroptions) {
    set_has_advancedasroptions();
  } else {
    clear_has_advancedasroptions();
  }
  // @@protoc_insertion_point(field_set_allocated:ConnectionRequest.advancedASROptions)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AdvancedASROptions::kPartialResultsFieldNumber;
const int AdvancedASROptions::kBiometryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AdvancedASROptions::AdvancedASROptions()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_request_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:AdvancedASROptions)
}
AdvancedASROptions::AdvancedASROptions(const AdvancedASROptions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  biometry_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_biometry()) {
    biometry_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.biometry_);
  }
  partial_results_ = from.partial_results_;
  // @@protoc_insertion_point(copy_constructor:AdvancedASROptions)
}

void AdvancedASROptions::SharedCtor() {
  _cached_size_ = 0;
  biometry_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  partial_results_ = true;
}

AdvancedASROptions::~AdvancedASROptions() {
  // @@protoc_insertion_point(destructor:AdvancedASROptions)
  SharedDtor();
}

void AdvancedASROptions::SharedDtor() {
  biometry_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void AdvancedASROptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AdvancedASROptions::descriptor() {
  protobuf_request_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_request_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AdvancedASROptions& AdvancedASROptions::default_instance() {
  protobuf_request_2eproto::InitDefaults();
  return *internal_default_instance();
}

AdvancedASROptions* AdvancedASROptions::New(::google::protobuf::Arena* arena) const {
  AdvancedASROptions* n = new AdvancedASROptions;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AdvancedASROptions::Clear() {
// @@protoc_insertion_point(message_clear_start:AdvancedASROptions)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_biometry()) {
      GOOGLE_DCHECK(!biometry_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*biometry_.UnsafeRawStringPointer())->clear();
    }
    partial_results_ = true;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool AdvancedASROptions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:AdvancedASROptions)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool partial_results = 1 [default = true];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_partial_results();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &partial_results_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string biometry = 24;
      case 24: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(194u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_biometry()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->biometry().data(), this->biometry().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "AdvancedASROptions.biometry");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:AdvancedASROptions)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:AdvancedASROptions)
  return false;
#undef DO_
}

void AdvancedASROptions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:AdvancedASROptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool partial_results = 1 [default = true];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->partial_results(), output);
  }

  // optional string biometry = 24;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->biometry().data(), this->biometry().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "AdvancedASROptions.biometry");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      24, this->biometry(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:AdvancedASROptions)
}

::google::protobuf::uint8* AdvancedASROptions::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:AdvancedASROptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool partial_results = 1 [default = true];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->partial_results(), target);
  }

  // optional string biometry = 24;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->biometry().data(), this->biometry().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "AdvancedASROptions.biometry");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        24, this->biometry(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AdvancedASROptions)
  return target;
}

size_t AdvancedASROptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AdvancedASROptions)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional string biometry = 24;
    if (has_biometry()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->biometry());
    }

    // optional bool partial_results = 1 [default = true];
    if (has_partial_results()) {
      total_size += 1 + 1;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AdvancedASROptions::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:AdvancedASROptions)
  GOOGLE_DCHECK_NE(&from, this);
  const AdvancedASROptions* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AdvancedASROptions>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:AdvancedASROptions)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:AdvancedASROptions)
    MergeFrom(*source);
  }
}

void AdvancedASROptions::MergeFrom(const AdvancedASROptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:AdvancedASROptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_biometry();
      biometry_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.biometry_);
    }
    if (cached_has_bits & 0x00000002u) {
      partial_results_ = from.partial_results_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void AdvancedASROptions::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:AdvancedASROptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AdvancedASROptions::CopyFrom(const AdvancedASROptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AdvancedASROptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AdvancedASROptions::IsInitialized() const {
  return true;
}

void AdvancedASROptions::Swap(AdvancedASROptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AdvancedASROptions::InternalSwap(AdvancedASROptions* other) {
  biometry_.Swap(&other->biometry_);
  std::swap(partial_results_, other->partial_results_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AdvancedASROptions::GetMetadata() const {
  protobuf_request_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_request_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AdvancedASROptions

// optional bool partial_results = 1 [default = true];
bool AdvancedASROptions::has_partial_results() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void AdvancedASROptions::set_has_partial_results() {
  _has_bits_[0] |= 0x00000002u;
}
void AdvancedASROptions::clear_has_partial_results() {
  _has_bits_[0] &= ~0x00000002u;
}
void AdvancedASROptions::clear_partial_results() {
  partial_results_ = true;
  clear_has_partial_results();
}
bool AdvancedASROptions::partial_results() const {
  // @@protoc_insertion_point(field_get:AdvancedASROptions.partial_results)
  return partial_results_;
}
void AdvancedASROptions::set_partial_results(bool value) {
  set_has_partial_results();
  partial_results_ = value;
  // @@protoc_insertion_point(field_set:AdvancedASROptions.partial_results)
}

// optional string biometry = 24;
bool AdvancedASROptions::has_biometry() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void AdvancedASROptions::set_has_biometry() {
  _has_bits_[0] |= 0x00000001u;
}
void AdvancedASROptions::clear_has_biometry() {
  _has_bits_[0] &= ~0x00000001u;
}
void AdvancedASROptions::clear_biometry() {
  biometry_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_biometry();
}
const ::std::string& AdvancedASROptions::biometry() const {
  // @@protoc_insertion_point(field_get:AdvancedASROptions.biometry)
  return biometry_.GetNoArena();
}
void AdvancedASROptions::set_biometry(const ::std::string& value) {
  set_has_biometry();
  biometry_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:AdvancedASROptions.biometry)
}
#if LANG_CXX11
void AdvancedASROptions::set_biometry(::std::string&& value) {
  set_has_biometry();
  biometry_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:AdvancedASROptions.biometry)
}
#endif
void AdvancedASROptions::set_biometry(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_biometry();
  biometry_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:AdvancedASROptions.biometry)
}
void AdvancedASROptions::set_biometry(const char* value, size_t size) {
  set_has_biometry();
  biometry_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:AdvancedASROptions.biometry)
}
::std::string* AdvancedASROptions::mutable_biometry() {
  set_has_biometry();
  // @@protoc_insertion_point(field_mutable:AdvancedASROptions.biometry)
  return biometry_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AdvancedASROptions::release_biometry() {
  // @@protoc_insertion_point(field_release:AdvancedASROptions.biometry)
  clear_has_biometry();
  return biometry_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AdvancedASROptions::set_allocated_biometry(::std::string* biometry) {
  if (biometry != NULL) {
    set_has_biometry();
  } else {
    clear_has_biometry();
  }
  biometry_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), biometry);
  // @@protoc_insertion_point(field_set_allocated:AdvancedASROptions.biometry)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
